# This Source Code Form is subject to the terms of the Mozilla Public
# License, v. 2.0. If a copy of the MPL was not distributed with this
# file, You can obtain one at http://mozilla.org/MPL/2.0/.

# Include to use Makefile under "skus" directory in common
# Migrate to OpenTofu since April 2025
include ../tofu-in-common.mk
